import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertTriangle,Check,Clock3,Copy,ExternalLink,RefreshCw,Search,Trash2,Wifi,WifiOff} from 'lucide-react';
import './index.css';

const CODERE_URL='https://www.codere.mx/';
const REF={
 MLB:[
  {id:'mlb-1',event:'Milwaukee Brewers vs San Diego Padres',selection:'Milwaukee +1.5 carreras',price:-160,prob:70,kind:'reference',market:'Run line',graph:[70,62,57]},
  {id:'mlb-2',event:'San Diego Padres vs Milwaukee Brewers · J2',selection:'Ambos equipos anotan 2+ carreras',price:-140,prob:62,kind:'reference',market:'Carreras por equipo',graph:[62,58,54]},
  {id:'mlb-3',event:'San Diego Padres vs Milwaukee Brewers',selection:'Más de 6.5 carreras totales',price:-110,prob:57,kind:'reference',market:'Total carreras',graph:[57,55,52]}],
 NFL:[
  {id:'nfl-1',event:'Buffalo Bills vs New England Patriots',selection:'Más de 33.5 puntos',price:-115,prob:58,kind:'reference',market:'Total puntos',graph:[58,64,61]},
  {id:'nfl-2',event:'Kansas City Chiefs vs Las Vegas Raiders',selection:'Más de 1.5 pases de TD',price:-180,prob:76,kind:'reference',market:'TD de jugador',graph:[76,72,68]},
  {id:'nfl-3',event:'Kansas City Chiefs vs Las Vegas Raiders',selection:'Doble oportunidad Chiefs',price:-350,prob:88,kind:'reference',market:'Resultado',graph:[88,84,81]}],
 LMX:[
  {id:'lmx-1',event:'Liga MX · próximos partidos',selection:'Más de 7.5 córners',price:-160,prob:72,kind:'reference',market:'Total córners',graph:[72,69,65]},
  {id:'lmx-2',event:'Liga MX · delantero titular',selection:'Más de 0.5 tiros a puerta',price:-200,prob:80,kind:'reference',market:'Tiros a puerta',graph:[80,76,73]},
  {id:'lmx-3',event:'Liga MX · mediocampista ofensivo',selection:'Más de 0.5 tiros totales',price:-260,prob:85,kind:'reference',market:'Tiros totales',graph:[85,82,78]}]
};
const TABS=[['MLB','MLB'],['NFL','NFL'],['LMX','Liga MX · props']];
const ICONS={MLB:'⚾',NFL:'🏈',LMX:'⚽'};
function americanToDecimal(a){return a>0?1+a/100:1+100/Math.abs(a)}
function implied(a){return 1/americanToDecimal(a)}
function fairAmerican(p){if(p<=0)return 0;if(p<=.5)return 100/p-100;return -(100*p/(1-p))}
function fmtAmerican(a){return a>0?`+${Math.round(a)}`:`${Math.round(a)}`}
function vigFree(prices){const ps=prices.map(implied);const sum=ps.reduce((a,b)=>a+b,0);return ps.map(p=>p/sum)}
function normalizeEvent(event,market,bookmaker){const outcomes=market.outcomes||[];if(!outcomes.length)return[];const probs=vigFree(outcomes.map(o=>o.price));return outcomes.map((o,i)=>({event:`${event.away_team} vs ${event.home_team}`,selection:`${o.name}${o.point!=null?` ${o.point}`:''}`,price:o.price,prob:Math.round(probs[i]*1000)/10,kind:'live',bookmaker,market:market.key,id:`${event.id}-${market.key}-${i}`,time:event.commence_time,home:event.home_team,away:event.away_team}))}
async function oddsFetch(sport,markets,signal){const url=`/api/odds?sport=${encodeURIComponent(sport)}&markets=${encodeURIComponent(markets)}`;const r=await fetch(url,{signal});if(r.status===429)throw Object.assign(new Error('rate-limit'),{code:429});if(!r.ok)throw new Error(`api-${r.status}`);return r.json()}
async function loadLive(tab,signal){if(tab==='MLB'){const data=await oddsFetch('baseball_mlb','h2h,spreads,totals',signal);return pickBest(data,'MLB')}if(tab==='NFL'){const data=await oddsFetch('americanfootball_nfl','h2h,spreads,totals',signal);return pickBest(data,'NFL')}const data=await oddsFetch('soccer_mexico_ligamx','h2h,spreads,totals',signal);return pickBest(data,'LMX')}
function pickBest(data,tab){const rows=[];for(const e of data||[])for(const b of e.bookmakers||[])for(const m of b.markets||[])rows.push(...normalizeEvent(e,m,b.title));const filtered=rows.filter(x=>x.market==='totals'||x.market==='spreads'||x.market==='h2h').sort((a,b)=>b.prob-a.prob);const uniq=[];const seen=new Set();for(const x of filtered){const k=`${x.event}|${x.selection}|${x.market}`;if(!seen.has(k)){seen.add(k);uniq.push(x)}if(uniq.length>=3)break}return uniq}
function SearchGraph({rows,tab}){const data=rows.slice(0,3);return <div className="chart-card"><div className="chart-head"><div><p className="eyebrow">{ICONS[tab]} GRÁFICO DEL DEPORTE</p><h3>{tab==='MLB'?'Perfil de carreras y líneas':tab==='NFL'?'Perfil de puntos y props':'Perfil de córners y tiros'}</h3></div><Activity size={17}/></div><div className="bars">{data.map((x,i)=><div className="bar-row" key={x.id}><div className="bar-label"><span>{i+1}. {x.selection}</span><b>{x.prob.toFixed(1)}%</b></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.min(100,x.prob)}%`}}/></div></div>)}</div><p className="chart-note">Visual de tasa implícita sin vig de las 3 mejores selecciones.</p></div>}
function CodereHelper({x}){const [copied,setCopied]=useState(false);const query=`${x.event} · ${x.selection} · ${x.market||'mercado'}`;const copy=async()=>{try{await navigator.clipboard.writeText(query);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};return <div className="codere-box"><div className="codere-title"><div><span className="codere-dot"/><b>Asistente Codere</b></div><span className="codere-mini">BÚSQUEDA</span></div><p>Este mercado puede ser difícil de localizar. Copia la búsqueda exacta y abre Codere para encontrar el evento.</p><div className="codere-query">{query}</div><div className="codere-actions"><button onClick={copy}><Copy size={14}/>{copied?'Copiado':'Copiar búsqueda'}</button><a href={CODERE_URL} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Abrir Codere</a></div></div>}
function App(){
 const [tab,setTab]=useState('MLB');const[live,setLive]=useState({MLB:null,NFL:null,LMX:null});const[updated,setUpdated]=useState(null);const[seconds,setSeconds]=useState(0);const[loading,setLoading]=useState(false);const[status,setStatus]=useState('reference');const[error,setError]=useState('');const[selected,setSelected]=useState([]);const[showCodere,setShowCodere]=useState(null);const abortRef=useRef(null);
 const current=useMemo(()=>live[tab]?.length?live[tab]:REF[tab],[live,tab]);const sorted=useMemo(()=>[...current].sort((a,b)=>b.prob-a.prob),[current]);
 const load=useCallback(async()=>{abortRef.current?.abort();const c=new AbortController();abortRef.current=c;setLoading(true);setError('');try{const data=await loadLive(tab,c.signal);if(data.length){setLive(x=>({...x,[tab]:data}));setStatus('live');setUpdated(Date.now());setSeconds(0)}else{setStatus('reference');setError('Sin mercados disponibles; mostrando referencia.')}}catch(e){if(e.name!=='AbortError'){setStatus('reference');setError(e.code===429?'Límite de API alcanzado; conservando la última data disponible.':'API no disponible; mostrando referencia.');if(!updated)setUpdated(Date.now());setSeconds(0)}}finally{setLoading(false)}},[tab,updated]);
 useEffect(()=>{load();return()=>abortRef.current?.abort()},[load]);useEffect(()=>{const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[]);useEffect(()=>{const id=setInterval(load,60000);return()=>clearInterval(id)},[load]);
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const selectedRows=useMemo(()=>TABS.flatMap(([key])=>(live[key]?.length?live[key]:REF[key])).filter(x=>selected.includes(x.id)),[selected,live]);const combo=useMemo(()=>{if(!selectedRows.length)return null;const p=selectedRows.reduce((a,x)=>a*x.prob/100,1);return{n:selectedRows.length,p,fair:fairAmerican(p)}},[selectedRows]);const clear=()=>setSelected([]);
 return <div className="app-shell"><main className="phone"><header className="header"><div className="brand"><div><div className="brand-row"><span className="brand-dot"/><h1>Boletín Codere MX</h1></div><p>Fin de semana · {new Intl.DateTimeFormat('es-MX',{dateStyle:'full'}).format(new Date())}</p></div><div className={`status ${status==='live'?'live':'ref'}`}>{status==='live'?<Wifi size={13}/>:<WifiOff size={13}/>} {status==='live'?'EN VIVO':'REFERENCIA'}</div></div><div className="update-row"><span><Clock3 size={14}/> {status==='live'?'Actualizado':'Último intento'} hace {seconds}s</span><button onClick={load} disabled={loading}><RefreshCw size={13} className={loading?'spin':''}/> Actualizar</button></div></header>
 <nav className="tabs">{TABS.map(([k,label])=><button key={k} onClick={()=>{setTab(k);setShowCodere(null)}} className={tab===k?'active':''}>{label}</button>)}</nav>
 <section className="content"><div className="section-head"><div><h2>{ICONS[tab]} Mejores selecciones</h2><span>3 ordenadas por acierto</span></div></div>{error&&<div className="alert"><AlertTriangle size={16}/><span>{error}</span></div>}
 <SearchGraph rows={sorted} tab={tab}/>
 <div className="cards">{sorted.map((x,i)=><article key={x.id} className="pick"><div className="pick-top"><div className="rank">{i+1}</div><div className="pick-main"><p className="event">{x.event}</p><p className="selection">{x.selection}</p></div><input aria-label="Agregar al parlay" type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/></div><div className="pick-bottom"><div><span className="price">{fmtAmerican(x.price)}</span><span className={x.kind==='live'?'live-label':'ref-label'}>{x.kind==='live'?'momio en vivo':'momio de referencia'}</span></div><b className="prob">{x.prob.toFixed(1)}%</b></div><div className="progress"><div style={{width:`${Math.min(100,x.prob)}%`}}/></div><div className="subline"><span>tasa implícita sin vig</span>{x.time&&<span>{new Date(x.time).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</span>}</div><button className="codere-find" onClick={()=>setShowCodere(showCodere===x.id?null:x.id)}><Search size={14}/> Encontrar en Codere</button>{showCodere===x.id&&<CodereHelper x={x}/>}</article>)}</div></section>
 </main>{combo&&<aside className="parlay"><div className="parlay-top"><div><p>Parlay · {combo.n} selección{combo.n===1?'':'es'}</p><strong className={combo.p<.5?'red':''}>{(combo.p*100).toFixed(1)}% <small>prob. combinada</small></strong></div><div className="fair"><span>Momio justo</span><b>{fmtAmerican(combo.fair)}</b></div></div>{combo.n>=4&&<p className="warning"><AlertTriangle size={13}/> 4+ selecciones: el acierto combinado cae rápidamente.</p>}<button onClick={clear}><Trash2 size={14}/> Limpiar</button></aside>}<footer className="footer">Tasas implícitas de mercado, no garantías. La probabilidad combinada es el producto de cada selección: a más patas, menor acierto real. <b>+18 · Juega con responsabilidad.</b></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
